// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pakai DATABASE_URL_VPS (bukan DATABASE_URL) agar tidak konflik
    // dengan env standar Vercel/Next.js dan mudah di-audit.
    url: process.env["DATABASE_URL_VPS"],
  },
});
